### ISSUE TITLE
Ruby benchmarking

### ISSUE THREAD

**Issue by mhewedy** [abarrak/why-compiled-languages#1]
I think if we in the ruby example used `while` loop instead. the performance would be better. cause it doesn't require any block definitions.

**Comment by abarrak** [comment]
Thanks for the tip @mhewedy.
Using `while` construct seems more optimized than `upto` and also a simple `for` loop. 
It gained ~ 2x speed output.

```ruby
sum = 0
i = 0

while i <= 1000000000 do
  sum += i
  i += 1
end

puts sum
```

```shell
$ time ruby src/ruby.rb 
500000000500000000

real	  0m21.774s
user   0m21.600s
sys	  0m0.087s
```

**Comment by mhewedy** [comment]
Thanks for the update
